### ISSUE TITLE
Suggestions: More configuration options? More Isolation?

### ISSUE THREAD

**Issue by zipacna** [7thCore/isrsrv-script#1]
Hello,

first up, Thanks for the Script. After some tinkering with the manual mode (running into the usual linux errors), I opted to use your script as intended (with a steam account I am willing to risk). Yet I got all the way to starting the server and failed there. But I will try that again, probably on a VM (ubuntu 20.04 instead of 18.04) later this week. Nevertheless, some Ideas:

Any chance some of my Suggestions below are worth it?
- If sudo is only needed for user creation, could you allow an Installation Option requiring an existing user (best already impersonated via `sudo su - username`). This way a passwordless user or otherwise configured user could be used.
- If a steam account is only needed to install the game-files / updates, could you allow an Installation Option to perform those manually (with the comfort of the other automatic options), so like sudo above, no credentials are risked. In your Guides Manual Section you already have the command needed listed.
- In case sudo is needed for more, would a docker container allow for more isolation? In case you are willing to go there, I could contribute (not a docker expert, but good enough to try it).
- In case the steam account is needed for more, would a Tutorial for Family Sharing on a second steam account (as it only needs temporary game access) work? Have not tried it myself yet, but this could be an alternative.
- Some Details on the SSK (Standalone Server Key if I understand it correctly)? This [Guide](https://steamcommunity.com/app/363360/discussions/0/530645446313237874/) might help. Is the SSK still a thing? was not able to find the described SSK.txt despite already having started a server (and tested it with an active server instance).
- A quick overview of the simplest / most important commands (not necessarily the same) would be good.
- Any chance of splitting the bash script 3000 LoC into something more readable?

Best Regards,
Zipacna

**Comment by 7thCore** [comment]
1. I could make it work with an existing user no problem.
2. Yes a steam account is only needed for installation and updates, I can make an option for manual intervention.
3. Sudo is needed only for installation so a docker container would not be needed.
4. The steam account is only needed for updates after installation. I also never tried this option. Will have to test it out.
5. SSK keys are no longer a thing so I need to remove that. The functions for it ware disabled but left in for just in case.
6. Did you try the -help command? Isn't it enough? 
7. I might try that but no promises.

**Comment by zipacna** [comment]
>If sudo is only needed for user creation, could you allow an Installation Option requiring an existing user (best already impersonated via sudo su - username). This way a passwordless user or otherwise configured user could be used.
> 1. I could make it work with an existing user no problem.
* [x] Much appreciated.
---
>If a steam account is only needed to install the game-files / updates, could you allow an Installation Option to perform those manually (with the comfort of the other automatic options), so like sudo above, no credentials are risked. In your Guides Manual Section you already have the command needed listed.
> 2. Yes a steam account is only needed for installation and updates, I can make an option for manual intervention.
* [x] Much appreciated.
---
>In case sudo is needed for more, would a docker container allow for more isolation? In case you are willing to go there, I could contribute (not a docker expert, but good enough to try it).
> 3. Sudo is needed only for installation so a docker container would not be needed.
* [x] Alright.
---
>In case the steam account is needed for more, would a Tutorial for Family Sharing on a second steam account (as it only needs temporary game access) work? Have not tried it myself yet, but this could be an alternative.
> 4. The steam account is only needed for updates after installation. I also never tried this option. Will have to test it out.
* [x] From what I understand from testing it myself, based on this [Steam FAQ](https://help.steampowered.com/en/faqs/view/57A7-503C-991F-E9A8), the library as a whole is shared and only Games without Third-Party Authentication (like a Origin Account) work. Which is the case for Interstellar Rift. It works within the constraints of the Temporary Access, so in case someone wants to go down this road, it is possible.
---
>Some Details on the SSK (Standalone Server Key if I understand it correctly)? This Guide might help. Is the SSK still a thing? was not able to find the described SSK.txt despite already having started a server (and tested it with an active server instance).
> 5. SSK keys are no longer a thing so I need to remove that. The functions for it ware disabled but left in for just in case.
* [x] Someone else might stumble over it, like I did, good to know SSK is no longer needed.
---
>A quick overview of the simplest / most important commands (not necessarily the same) would be good.
> 6. Did you try the -help command? Isn't it enough?
* [ ] Have to admit, I did not touch it in a few weeks, was using the Windows local hosting mostly, which might actually be good for a fresh view on it. Will get back to you on that one.
---
>Any chance of splitting the bash script 3000 LoC into something more readable?
> 7. I might try that but no promises.
* [x] Big Refactoring might be to tedious. No Problem, just an idea.

Thanks for commenting on my points, I would consider most as closed as you see fit, as mentioned above, will get back to you about the overview/help command.

**Comment by 7thCore** [comment]
I'll leave it open and you can get back to me here. No need to open a new issue for this. Sorry for the late reply. Regarding the docker container, if you wish to create one you can do so but do maintain it and credit me for the script.

**Comment by 7thCore** [comment]
I did a lot of changes in the past week. Let me know what you think of them.
