### ISSUE TITLE
Line 2239: syntax error: unexpected end of file

### ISSUE THREAD

**Issue by survaaki** [7thCore/isrsrv-script#2]
Hi. Did the .deb installation on Ubuntu 20.04 but hit this error. Any ideas?

**Comment by 7thCore** [comment]
It's a high possibility that I missed a } to close a function. I'll go through the code and have an update available in about 30 minutes.

Edit: found it. The } is missing on line 156.

**Comment by 7thCore** [comment]
@survaaki should be fixed. Download the new .deb package and install it. After that run `systemctl --user daemon-reload` as the isrsrv user. Also let me know if it solved the problem.

**Comment by survaaki** [comment]
Yeah, that fixed it for me. Thank you!
