### ISSUE TITLE
config_steam installs then exits with Error! App '363360' state is 0x10C after update job.

### ISSUE THREAD

**Issue by survaaki** [7thCore/isrsrv-script#3]
From running bash -x I see the command is:

 steamcmd +@sSteamCmdForcePlatformType windows +force_install_dir /srv/isrsrv/server/drive_c/Games/InterstellarRift +login \<redacted\> +app_update 363360 validate +quit
 
 I ran that manually but same error. This may have nothing to do with the script and be some Steam issue?

**Comment by 7thCore** [comment]
This is out of my hands because like you said, it is a SteamCMD error. I think the server does get installed regardless of that error.

**Comment by survaaki** [comment]
Thanks, I'll follow it up there.
